# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClasificacionRedes
                                 A QGIS plugin
 Este plugin clasifica las redes hídricas por medio de una etapa de enriquecimiento y otra de lógica difusa.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-17
        copyright            : (C) 2021 by Ramón Cruz Blanco
        email                : rcb00029@red.ujaen.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ClasificacionRedes class from file ClasificacionRedes.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .clasificacion_redes import ClasificacionRedes
    return ClasificacionRedes(iface)
